language: r
dist: bionic
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

after_success:
  # Lint
  - Rscript -e 'lintr::lint_package()'
  # Codecov
  - Rscript -e 'covr::codecov()'
  # Goodpractice
  - travis_wait 60 Rscript -e 'goodpractice::gp()'

